---
author: |
  | William Findlay
title: |
  | Section 1: UML
date: \today
bibliography: /home/housedhorse/.bibs/uni.bib
csl: /home/housedhorse/.bibs/ieee.csl
subparagraph: yes
header-includes: |
  ``` {=latex}
  \usepackage{float}
  \usepackage{listings}
  \usepackage[hang,bf]{caption}
  \usepackage{framed}
  \usepackage[section]{placeins}
  \usepackage[dvipsnames]{xcolor}

  \usepackage{pifont}

  \allowdisplaybreaks

  % fancy headers/footers
  \makeatletter
  \usepackage{fancyhdr}
  \lhead{\@author}
  \chead{}
  \rhead{\@title}
  \lfoot{}
  \cfoot{\thepage}
  \rfoot{}
  \renewcommand{\headrulewidth}{0.4pt}

  \usepackage{amsmath, amsfonts,amssymb, amsthm}
  \usepackage{siunitx}
  \usepackage[boxruled,lined,linesnumbered,titlenumbered]{algorithm2e}

  \usepackage{setspace}
  \usepackage{changepage}
  \usepackage[explicit]{titlesec}
  \usepackage{aliascnt}

  \floatplacement{figure}{!htb}
  \floatplacement{table}{!htb}
  \floatplacement{listing}{!htb}
  \lstset{numbers=left,breaklines=true,frame=single,language=C,captionpos=b,abovecaptionskip={\abovecaptionskip},
  belowcaptionskip={\belowcaptionskip},aboveskip=\intextsep,showstringspaces=false,identifierstyle=\color{Blue},
  commentstyle={\color{OliveGreen}},keywordstyle={\bfseries\color{Orange}}}
  \setlength{\captionmargin}{1in}

  \newgeometry{margin=1in}

  \newtheoremstyle{plain}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\itshape}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{definition}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{remark}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\itshape} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \theoremstyle{plain}

  % define theorem
  \newtheorem{theorem}{Theorem}[section]
  \providecommand*{\theoremautorefname}{Theorem}

  % define lemma
  \newtheorem{lemma}{Lemma}[section]
  \providecommand*{\lemmaautorefname}{Lemma}

  % define claim
  \newtheorem{claim}{Claim}[section]
  \providecommand*{\claimautorefname}{Claim}

  % define corollary
  \newtheorem{corollary}{Corollary}[section]
  \providecommand*{\corollaryautorefname}{Corollary}

  % define proposition
  \newtheorem{proposition}{Proposition}[section]
  \providecommand*{\propositionautorefname}{Proposition}

  % define conjecture
  \newtheorem{conjecture}{Conjecture}[section]
  \providecommand*{\conjectureautorefname}{Conjecture}

  \theoremstyle{remark}

  % define observation
  \newtheorem{observation}{Observation}[section]
  \providecommand*{\observationautorefname}{Observation}

  % define remark
  \newtheorem{remark}{Remark}[section]
  \providecommand*{\remarkautorefname}{Remark}

  \theoremstyle{definition}

  % define example
  \newtheorem{example}{Example}[section]
  \providecommand*{\exampleautorefname}{Example}

  % define definition
  \newtheorem{definition}{Definition}[section]
  \providecommand*{\definitionautorefname}{Definition}

  \newcommand{\blackbox}{\hfill$\blacksquare$}
  \usepackage{tikz}
  \newcommand*\circled[1]{\tikz[baseline=(char.base)]{
              \node[shape=circle,draw,inner sep=2pt] (char) {#1};}}

  \renewcommand{\labelitemi}{\large$\bullet$}
  \renewcommand{\labelitemii}{\ding{226}}
  \renewcommand{\labelitemiii}{\tiny$\blacksquare$}
  \renewcommand{\labelitemiv}{\small$\triangleright$}

  \titleformat{\paragraph}
  {\itshape}
  {}
  {0em}
  {\underline{#1}}[ ]
  \titleformat{\subparagraph}
  {\itshape}
  {}
  {0em}
  {#1}[ ]

  \let\lil\lstinputlisting
  \usepackage{afterpage}
  \usepackage{xcolor}
  \hypersetup{colorlinks, allcolors=., urlcolor=blue}

  \usepackage{etoolbox}% http://ctan.org/pkg/etoolbox
  \makeatletter
  \patchcmd{\lst@GLI@}% <command>
    {\def\lst@firstline{#1\relax}}% <search>
    {\def\lst@firstline{#1\relax}\def\lst@firstnumber{#1\relax}}% <replace>
    {\typeout{listings firstnumber=firstline}}% <success>
    {\typeout{listings firstnumber not set}}% <failure>
  \makeatother
  ```
output:
  pdf_document:
    number_sections: true
    fig_crop: true
    fig_caption: true
    keep_tex: false
---
\newpage
\pagestyle{plain}
\tableofcontents
\newpage
\pagestyle{fancy}

# UML Overview
- **unified modeling language**
- what is it?
  - a tool for **expressing system models**
    - functional
    - dynamic
    - object

## The UML Family
- each notation is for a **specific model**
- models and notations
    - functional
      - use case diagrams
    - dynamic
      - state machine diagrams
      - sequence diagrams
      - activity diagrams
    - object
      - class diagrams


# Use Case Diagrams
- what is a use case?
  - behavior observed by **external entities**
  - entities called **actors**
    - end users
      - different roles
    - external systems
      - systems that our system will **interact with**
  - can also be represented *textually*
    - table-based
- what are use case diagrams?
  - graphical representation of use cases
- purpose
  - system boundaries
  - **always use a box in the drawing**

## Some Rules
  - the box is important
  - ovals for use cases
    - use cases are labeled with verb phrases
  - actors
    - draw as stick figures
    - an actor is a **role**
    - not necessarily a person
    - a person can have more than one role
- in our project
  - SQL and Qt are **not external roles**
  - they are part of the system

![An example of a use case diagram.
The stick figures are actors.
The bubbles inside the box are use cases.
A use case is always labeled with a verb phrase.](03/use-case.png){width=60%}


# Class Diagrams
- graphical representation of classes and **objects**
- purpose
  - describe a system
  - in terms of **classes**
  - include
    - attributes
    - operations
    - associations

![An example of a class diagram.
Each class is represented by a box
with a name, attributes, and operations
and is connected to other classes by associations.](03/class.png)

## Some Rules
- three sections
  - class name
  - attributes
  - operations
- attributes
  - access specifier
    - `+` public
    - `#` protected
    - `-` private
  - name
  - `:` followed by data type
- operations
  - access specifier
    - `+` public
    - `#` protected
    - `-` private
  - name
  - parameters
    - input
    - output
    - input-output
- associations
  - direction
    - directed
    - undirected
  - types
    - inheritance
      - aggregation
    - composition
  - cardinality
    - none-to-many `0..*`
    - one-to-many `1..*`
    - etc.

## Object Diagrams
- underlined $\implies$ specific instance
  - also include an instance name before a `:` in front of class
  - sometimes just a `:` if instance name is implied

![An example of an object diagram.
Note that the object name is not always
specified if it is obvious.](03/object.png)


# State Machine Diagrams
- graphical representation of the **state** of a **single objects**
  - only more complicated ones
  - some may not have any states
- purpose
  - set of states
  - transitions from one state to another
  - state:
    - attribute values for an object
  - transition:
    - conditions under which an object changes state

![An example of a state machine diagram
for a course registration request.
The bubbles are the states and the labeled
arrows are the transitions. Also note that
a state can have one or more transitions to itself.](03/state-machine.png)

## How it Looks
- states in bubbles
- arrows (transitions)
  - labels are mandatory
    - except labels **from start** or **to end**
  - labels are the transitions
  - you can have arrows from a state to itself



# Activity Diagrams
- we won't use these a lot
- what are they?
  - system behavior
    - sequencing
    - coordination
- purpose
  - describe sequential steps in processing
    - control flow
    - concurrency

![An example of an activity diagram.
The two halves of the sqare are called "swim lanes".
You can also have one swim lane or more than two swim lanes.](03/activity.png)



# Sequence Diagrams


# Packages
