---
author: |
  | William Findlay
title: |
  | COMP3004 Notes
date: \today
bibliography: /home/housedhorse/.bibs/uni.bib
csl: /home/housedhorse/.bibs/ieee.csl
subparagraph: yes
header-includes: |
  ``` {=latex}
  \usepackage{float}
  \usepackage{listings}
  \usepackage[hang,bf]{caption}
  \usepackage{framed}
  \usepackage[section]{placeins}

  \allowdisplaybreaks

  % fancy headers/footers
  \makeatletter
  \usepackage{fancyhdr}
  \lhead{\@author}
  \chead{}
  \rhead{\@title}
  \lfoot{}
  \cfoot{\thepage}
  \rfoot{}
  \renewcommand{\headrulewidth}{0.4pt}

  \usepackage{amsmath, amsfonts,amssymb, amsthm}
  \usepackage{siunitx}
  \usepackage[boxruled,lined,linesnumbered,titlenumbered]{algorithm2e}

  \usepackage{setspace}
  \usepackage{changepage}
  \usepackage[explicit]{titlesec}
  \usepackage{aliascnt}

  \floatplacement{figure}{!htb}
  \floatplacement{table}{!htb}
  \floatplacement{listing}{!htb}
  \lstset{mathescape=true,numbers=left,breaklines=true,frame=single,language=C++,captionpos=b,abovecaptionskip={\abovecaptionskip},belowcaptionskip={\belowcaptionskip},aboveskip=\intextsep}
  \setlength{\captionmargin}{1in}

  \newgeometry{margin=1in}

  \newtheoremstyle{plain}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\itshape}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{definition}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{remark}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\itshape} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \theoremstyle{plain}

  % define theorem
  \newtheorem{theorem}{Theorem}[section]
  \providecommand*{\theoremautorefname}{Theorem}

  % define lemma
  \newtheorem{lemma}{Lemma}[section]
  \providecommand*{\lemmaautorefname}{Lemma}

  % define claim
  \newtheorem{claim}{Claim}[section]
  \providecommand*{\claimautorefname}{Claim}

  % define corollary
  \newtheorem{corollary}{Corollary}[section]
  \providecommand*{\corollaryautorefname}{Corollary}

  % define proposition
  \newtheorem{proposition}{Proposition}[section]
  \providecommand*{\propositionautorefname}{Proposition}

  % define conjecture
  \newtheorem{conjecture}{Conjecture}[section]
  \providecommand*{\conjectureautorefname}{Conjecture}

  \theoremstyle{remark}

  % define observation
  \newtheorem{observation}{Observation}[section]
  \providecommand*{\observationautorefname}{Observation}

  % define remark
  \newtheorem{remark}{Remark}[section]
  \providecommand*{\remarkautorefname}{Remark}

  \theoremstyle{definition}

  % define example
  \newtheorem{example}{Example}[section]
  \providecommand*{\exampleautorefname}{Example}

  % define definition
  \newtheorem{definition}{Definition}[section]
  \providecommand*{\definitionautorefname}{Definition}

  \newcommand{\blackbox}{\hfill$\blacksquare$}
  \usepackage{tikz}
  \newcommand*\circled[1]{\tikz[baseline=(char.base)]{
              \node[shape=circle,draw,inner sep=2pt] (char) {#1};}}

  \renewcommand{\labelitemi}{$\bullet$}
  \renewcommand{\labelitemiii}{\textbullet}
  \renewcommand{\labelitemiv}{-}

  \titleformat{\paragraph}
  {\itshape}
  {}
  {0em}
  {\underline{#1}}[ ]
  \titleformat{\subparagraph}
  {\itshape}
  {}
  {0em}
  {#1}[ ]

  \let\lil\lstinputlisting
  \usepackage{afterpage}
  \usepackage{xcolor}
  \hypersetup{colorlinks, allcolors=., urlcolor=blue}
  ```
output:
  pdf_document:
    number_sections: true
    fig_crop: true
    fig_caption: true
    keep_tex: false
---
\newpage
\pagestyle{plain}
\tableofcontents
\newpage
\pagestyle{fancy}

# Introduction

## Development Life Cycle

### Requirements Analysis
- requirements
  - functional
  - non-functional
- functional model
- dynamic model
- analysis object model

### High Level System Design
- subsystem decomposition
- system architecture strategies

### Detailed Object Design
- detailed object model
  - class diagrams
- design patterns and contracts

### Implementation
- map associations to
  - collections (easy)
  - storage (hard)

### Testing
- unit testing
- integration testing
- system testing

## Team Work
- we can't each do a part and put it together
- we have to do it all together

## Tools
- VirtualBox
- VM
  - Qt Framework comes with it
  - Dia comes with it
- C++

## Textbook
- textbook is a good indication of how much detail you need for deliverables
  - follow the arena case study
  - perfect level of detail

# Software Engineering Overview

## Definitions

- software engineering
  - software
    - code
    - application
  - engineering
    - technical process for achieving a task
    - building something
  - what **is** software engineering
    - requirements analysis
    - building software
  - what is **not** software engineering
    - building tiny little program
- system
  - what is a system in software engineering?
    - a very **large** piece of software
    - so big, we don't call it
      - a program
      - an application
- we need a **reliable process**
  - a *recipe*
  - why?
  - wanted:
    - **reliable** systems
    - **modifiable** systems
      - we don't want to throw away code to add a new feature
  - we need a **plan**

### The Plan
- two ingredients
  - technical
  - management

#### Technical Aspects
- **understand** the problem
  - *how do we do this?*
  - **ask the client**
- figure out an **optimal solution**

#### Management Aspects
- keep things **on track**
- plan for change
  - *anything can change at any time*

## Technical Aspects

### Application Domain
- **relevant to the problem**
- the *client's world*
- airport example
  - planes
  - runways
  - gates
  - passengers
  - luggage
- we are **not** experts here
  - the *client* is

### Solution Domain
- the **fix** for the problem
- *our* world
- GUI
- design patterns

### Building Models
- what is a model?
- why do we need a model?
- what can go wrong?
- types
  - functional
  - dynamic
  - object

#### The Point of Models
- look at a small scale version
  - don't necessarily build a small scale version
  - look at some different *views* of it
- figure out
  - *how will it work?*

#### Modeling the Application Domain
- requirements analysis
  - **describe** problem to be solved
  - **describe** system requirements
  - **identify** objects required

## Management Aspects
- communication tools
- configuration management
- rationale management
- software development process

### Dealing With Change
- the earlier the better

### The Stakeholders
- client
  - users
  - interacts with
    - project managers
    - requirements team manager
      - QA
- development team
  - project manager
  - architect
  - analyst
  - designers
  - programmers
  - testers
  - operations

## Software Development Phases
